### ISSUE TITLE
Decoder for Structure serials not working

### ISSUE THREAD

**Issue by uinnn** [charleskorn/kaml#142]
I'm getting this error:

`kotlin.UninitializedPropertyAccessException: lateinit property currentValueDecoder has not been initialized
        at com.charleskorn.kaml.YamlMapLikeInputBase.getCurrentValueDecoder(YamlInput.kt:244) ~[?:?]
        at com.charleskorn.kaml.YamlMapLikeInputBase.fromCurrentValue(YamlInput.kt:269) ~[?:?]
        at com.charleskorn.kaml.YamlMapLikeInputBase.decodeString(YamlInput.kt:256) ~[?:?]
        at kotlinx.serialization.encoding.AbstractDecoder.decodeStringElement(AbstractDecoder.kt:58) ~[?:?]`
        
I using this for serial structures, this works perfectly when i encode the structure but not when decode
using `kotlin 1.5.0`, `kotlin serialization 1.2.1` and `kaml 0.33.0`

**Comment by uinnn** [comment]
I tested without using sequentially and works perfect, but you maybe can put support for decode sequentially? Well, i will close this issue.

**Comment by charleskorn** [comment]
Hi @uinnn, could you share a repository that demonstrates this issue?

**Comment by uinnn** [comment]
Here: [https://gist.github.com/uinnn/08a15a8e94e4ae9798c14b5bc91d7a7e](code)
