### ISSUE TITLE
Primitive serialization not working?

### ISSUE THREAD

**Issue by Kadeluxe** [charleskorn/kaml#300]
### Describe the bug

[Primitive deserialization](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#primitive-serializer=) is not working.

### Reproduction repo

This serializer class works for JSON but not for YAML.

```
@Serializer(forClass = Duration::class)
object DurationSerializer : KSerializer<Duration> {
  override val descriptor = PrimitiveSerialDescriptor("Duration", PrimitiveKind.STRING)
  override fun serialize(encoder: Encoder, value: Duration) = encoder.encodeString(value.toString())
  override fun deserialize(decoder: Decoder): Duration = Duration.parse(decoder.decodeString())
}
```

### Steps to reproduce

Create simple primitive serializer as described in [docs](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#primitive-serializer=) and try to deserialize a value.

### Expected behaviour

Same behaviour as in JSON.

It works if I change deserializer to this:
```
  override fun deserialize(decoder: Decoder): Duration {
    val t = (decoder.beginStructure(descriptor) as AbstractDecoder)
    return Duration.parse(t.decodeString().also { t.endStructure(descriptor) })
  }
```
but this way is not compatible with JSON and doesn't seem clean in general.

### Actual behaviour

```
java.lang.IllegalStateException: Must call beginStructure() and use returned Decoder
        at com.charleskorn.kaml.YamlContextualInput.decodeValue(YamlContextualInput.kt:29) ~[?:?]
        at kotlinx.serialization.encoding.AbstractDecoder.decodeString(AbstractDecoder.kt:34) ~[?:?]
        at com.charleskorn.kaml.YamlMapLikeInputBase$decodeString$1.invoke(YamlMapLikeInputBase.kt:39) ~[?:?]
        at com.charleskorn.kaml.YamlMapLikeInputBase$decodeString$1.invoke(YamlMapLikeInputBase.kt:39) ~[?:?]
        at com.charleskorn.kaml.YamlMapLikeInputBase.fromCurrentValue(YamlMapLikeInputBase.kt:52) ~[?:?]
        at com.charleskorn.kaml.YamlMapLikeInputBase.decodeString(YamlMapLikeInputBase.kt:39) ~[?:?]
        ...
        at kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:260) ~[?:?]
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:16) ~[?:?]
        at com.charleskorn.kaml.YamlInput.decodeSerializableValue(YamlInput.kt:103) ~[?:?]
        at kotlinx.serialization.ContextualSerializer.deserialize(ContextualSerializer.kt:67) ~[?:?]
        at kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:260) ~[?:?]
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:16) ~[?:?]
        at com.charleskorn.kaml.YamlInput.decodeSerializableValue(YamlInput.kt:103) ~[?:?]
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43) ~[?:?]
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70) ~[?:?]
        ...
        at kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:260) ~[?:?]
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:16) ~[?:?]
        at com.charleskorn.kaml.YamlInput.decodeSerializableValue(YamlInput.kt:103) ~[?:?]
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43) ~[?:?]
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70) ~[?:?]
        ...
        at kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:260) ~[?:?]
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:16) ~[?:?]
        at com.charleskorn.kaml.YamlInput.decodeSerializableValue(YamlInput.kt:103) ~[?:?]
        at com.charleskorn.kaml.Yaml.decodeFromReader(Yaml.kt:55) ~[?:?]
        at com.charleskorn.kaml.Yaml.decodeFromStream(Yaml.kt:48) ~[?:?]
```

### Version information

```plain text
0.46.0
```

**Comment by russellbanks** [comment]
Could this be re-opened @charleskorn? I currently have to have twice the serializers as I should do in my project as I have to have separate ones for Json compared to Yaml:

Json:
```kotlin
object JsonLocalDateSerializer : KSerializer<LocalDate> {
    override val descriptor = PrimitiveSerialDescriptor(LocalDate::class.simpleName as String, PrimitiveKind.STRING)

    override fun serialize(encoder: Encoder, value: LocalDate) {
        encoder.encodeString(value.toString())
    }

    override fun deserialize(decoder: Decoder): LocalDate {
        return LocalDate.parse(decoder.decodeString())
    }
}
```

Yaml:
```kotlin
object YamlLocalDateSerializer : KSerializer<LocalDate> {
    override val descriptor = PrimitiveSerialDescriptor(LocalDate::class.simpleName as String, PrimitiveKind.STRING)

    override fun serialize(encoder: Encoder, value: LocalDate) {
        encoder.encodeString(value.toString())
    }

    override fun deserialize(decoder: Decoder): LocalDate {
        return LocalDate.parse(decoder.beginStructure(descriptor).decodeStringElement(descriptor, 0))
    }
}

```

**Comment by russellbanks** [comment]
@charleskorn Can you freeze this

**Comment by OptimumCode** [comment]
Hi, @russellbanks. This issue might have been resolved when https://github.com/charleskorn/kaml/issues/568 was closed. Could you please check version [0.61.0](https://github.com/charleskorn/kaml/releases/tag/0.61.0) and let us know if you still have the problem?

**Comment by Kadeluxe** [comment]
Hey there, I revisited this library 3 years later and example in my first post works now. I think this can be closed now.
