### ISSUE TITLE
Support sequential decoding

### ISSUE THREAD

**Issue by dellisd** [charleskorn/kaml#366]
### Describe the problem you'd like to solve

This is related to #142, as kaml does not support sequential decoding in custom serializers.

For example:
```kotlin
@Serializable(with = CustomSerializer::class)
data class Multi(val a: String, val b: String)

object CustomSerializer : KSerializer<Multi> {
    override val descriptor: SerialDescriptor = buildClassSerialDescriptor("Multi") {
        element<String>("a")
        element<String>("b")
    }
    override fun deserialize(decoder: Decoder): Multi {
        return decoder.decodeStructure(descriptor) {
            Multi(
                decodeStringElement(descriptor, 0),
                decodeStringElement(descriptor, 1)
            )
        }
    }
    override fun serialize(encoder: Encoder, value: Multi) = throw UnsupportedOperationException()
}

val input = """
b: This is B
a: This is A
 """.trimIndent()

val result = Yaml.decodeFromString(Multi.serializer(), input)
``` 

This will fail on the first `decodeStringElement` call with this error:
```
lateinit property currentValueDecoder has not been initialized
kotlin.UninitializedPropertyAccessException: lateinit property currentValueDecoder has not been initialized
	at com.charleskorn.kaml.YamlMapLikeInputBase.getCurrentValueDecoder(YamlMapLikeInputBase.kt:25)
	at com.charleskorn.kaml.YamlMapLikeInputBase.fromCurrentValue(YamlMapLikeInputBase.kt:50)
	at com.charleskorn.kaml.YamlMapLikeInputBase.decodeString(YamlMapLikeInputBase.kt:37)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeStringElement(AbstractDecoder.kt:58)
```

### Describe the solution you'd like

Support sequential decoding of elements as shown above.

### Describe alternatives you've considered

It is still possible to decode this structure manually, although the code looks much worse.

```kotlin
object CustomSerializer : KSerializer<Multi> {
    override val descriptor: SerialDescriptor = buildClassSerialDescriptor("Multi") {
        element<String>("a")
        element<String>("b")
    }
    override fun deserialize(decoder: Decoder): Multi {
        return decoder.decodeStructure(descriptor) {
          lateinit var a: String
          lateinit var b: String
          while (true) {
            when (decodeElementIndex(descriptor)) {
              0 -> a = decodeStringElement(descriptor, 0)
              1 -> b = decodeStringElement(descriptor, 1)
              DECODE_DONE -> break
            }
            Multi(a, b)
        }
    }
    override fun serialize(encoder: Encoder, value: Multi) = throw UnsupportedOperationException()
}
```

**Comment by charleskorn** [comment]
Thanks for the report @dellisd. I'm open to PRs that would add support for this if you're interested in contributing one.
