### ISSUE TITLE
an exception occurred while using the specified serializer in polymorphic serialization

### ISSUE THREAD

**Issue by 4o4E** [charleskorn/kaml#404]
### Describe the bug

```log
Exception in thread "main" kotlin.UninitializedPropertyAccessException: lateinit property currentValueDecoder has not been initialized
	at com.charleskorn.kaml.YamlMapLikeInputBase.getCurrentValueDecoder(YamlMapLikeInputBase.kt:25)
	at com.charleskorn.kaml.YamlMapLikeInputBase.fromCurrentValue(YamlMapLikeInputBase.kt:50)
	at com.charleskorn.kaml.YamlMapLikeInputBase.decodeInt(YamlMapLikeInputBase.kt:38)
	at com.charleskorn.kaml.YamlListInput.decodeInt(YamlListInput.kt:58)
	at top.e404.test.PotionEffectSerializer.deserialize(Extra.kt:29)
	at top.e404.test.PotionEffectSerializer.deserialize(Extra.kt:27)
	at kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:257)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:16)
	at com.charleskorn.kaml.YamlInput.decodeSerializableValue(YamlInput.kt:104)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:533)
	at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(CollectionSerializers.kt:80)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
	at kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:257)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:16)
	at com.charleskorn.kaml.YamlInput.decodeSerializableValue(YamlInput.kt:104)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
	at top.e404.test.TestExtra$$serializer.deserialize(Extra.kt:19)
	at top.e404.test.TestExtra$$serializer.deserialize(Extra.kt:19)
	at kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:257)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:16)
	at com.charleskorn.kaml.YamlInput.decodeSerializableValue(YamlInput.kt:104)
	at com.charleskorn.kaml.YamlPolymorphicInput.decodeSerializableValue(YamlPolymorphicInput.kt:100)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:533)
	at kotlinx.serialization.internal.AbstractPolymorphicSerializer.deserialize(AbstractPolymorphicSerializer.kt:57)
	at kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:257)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:16)
	at com.charleskorn.kaml.YamlInput.decodeSerializableValue(YamlInput.kt:104)
	at com.charleskorn.kaml.YamlPolymorphicInput.decodeSerializableValue(YamlPolymorphicInput.kt:100)
	at com.charleskorn.kaml.Yaml.decodeFromReader(Yaml.kt:54)
	at com.charleskorn.kaml.Yaml.decodeFromStream(Yaml.kt:47)
	at com.charleskorn.kaml.Yaml.decodeFromStream$default(Yaml.kt:46)
	at top.e404.test.ExtraKt.main(Extra.kt:41)
	at top.e404.test.ExtraKt.main(Extra.kt)
```

### Reproduction repo

example code

```kotlin
import com.charleskorn.kaml.PolymorphismStyle
import com.charleskorn.kaml.Yaml
import com.charleskorn.kaml.YamlConfiguration
import com.charleskorn.kaml.decodeFromStream
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.KSerializer
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.buildClassSerialDescriptor
import kotlinx.serialization.descriptors.element
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

@Serializable
sealed interface Extra

@Serializable
@SerialName("test")
data class TestExtra(
    val potions: MutableSet<@Serializable(PotionEffectSerializer::class) PotionEffect>,
) : Extra

class PotionEffect(val type: Int)

object PotionEffectSerializer : KSerializer<PotionEffect> {
    override val descriptor = buildClassSerialDescriptor(this::class.java.name) { element<Int>("type") }
    override fun deserialize(decoder: Decoder) = PotionEffect(decoder.decodeInt())
    override fun serialize(encoder: Encoder, value: PotionEffect) = encoder.encodeInt(value.type)
}

fun main() {
    val yaml = Yaml(configuration = YamlConfiguration(strictMode = false, polymorphismStyle = PolymorphismStyle.Property))
    val data = Thread.currentThread().contextClassLoader.getResourceAsStream("test.yml")!!.use {
        yaml.decodeFromStream<Extra>(it)
    }
    println(data)
}
```

test.yml

```yaml
type: test
potions:
  - { type: 1 }
```

### Steps to reproduce

Use the specified serializer in polymorphic serialization

### Expected behaviour

serialize normally

### Actual behaviour

can't serialize

### Version information

```plain text
fun kotlinx(id: String, version: String) = "org.jetbrains.kotlinx:kotlinx-$id:$version"
// serialization
implementation(kotlinx("serialization-core-jvm", "1.4.0"))
implementation(kotlinx("serialization-json", "1.4.0"))
// kaml
implementation("com.charleskorn.kaml:kaml:0.53.0")
```

**Comment by charleskorn** [comment]
It looks like the issue is that you're jumping straight to trying to read the value for `PotionEffect.type` without first reading the property name.

Each custom serializer needs to start and end with a `beginStructure` and `endStructure` pair, like this:

```kotlin
val input = decoder.beginStructure(descriptor) as YamlInput

...decode object here...

input.endStructure(descriptor)
```

You'll then need to loop through each decoded field with `input`, similar to [this example](https://github.com/batect/batect/blob/f69a9d4e6d899b68200e226441ba6a9d39b4347b/app/src/main/kotlin/batect/config/VolumeMount.kt#L91-L108).

**Comment by 4o4E** [comment]
Thank you for your answer. I know the reason for the problem
