### ISSUE TITLE
"java.util.NoSuchElementException: No value present" error if unquoted field value starts with "@"

### ISSUE THREAD

**Issue by kenyee** [charleskorn/kaml#407]
### Describe the bug

kaml doesn't tell the user which field is missing in a YAML file if it's a required field

Adding an extra field which has a great error msg showing what fields are allowed.  Would be nice if missing field name was included in the exception.

### Steps to reproduce

Create a data class with a required string field.
Create a YAML file to parse that has that field set to "@test" (no quotes).
Try parsing the YAML file.

### Expected behaviour

Should have a more descriptive field like "yaml macro '@test' not found".

### Actual behaviour

Stack trace:
```
Caused by: java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:148)
	at com.charleskorn.kaml.YamlParser.translateYamlEngineException(YamlParser.kt:75)
	at com.charleskorn.kaml.YamlParser.checkEvent(YamlParser.kt:67)
	at com.charleskorn.kaml.YamlParser.peekEvent(YamlParser.kt:53)
	at com.charleskorn.kaml.YamlNodeReader.readMapping(YamlNodeReader.kt:110)
	at com.charleskorn.kaml.YamlNodeReader.readFromEvent(YamlNodeReader.kt:63)
	at com.charleskorn.kaml.YamlNodeReader.readNodeAndAnchor(YamlNodeReader.kt:43)
	at com.charleskorn.kaml.YamlNodeReader.readNode(YamlNodeReader.kt:39)
	at com.charleskorn.kaml.YamlNodeReader.read(YamlNodeReader.kt:37)
	at com.charleskorn.kaml.Yaml.parseToYamlNodeFromReader(Yaml.kt:64)
	at com.charleskorn.kaml.Yaml.decodeFromReader(Yaml.kt:51)
	at com.charleskorn.kaml.Yaml.decodeFromString(Yaml.kt:43)
```

Looks like the bug is that e.contextMark is missing:
val contextMark = e.contextMark.get() 

### Version information

```plain text
0.53.0
```

**Comment by charleskorn** [comment]
Thanks for the bug report @kenyee. Could you share an example of a YAML document that causes this exception?
