### ISSUE TITLE
Allow non strict parsing

### ISSUE THREAD

**Issue by fvasco** [charleskorn/kaml#5]
Please implement a non strict Yaml parser, similar to `Json.strictMode`, to ignore unmapped keys.

Error on version 0.11.0:

```
com.charleskorn.kaml.UnknownPropertyException: Unknown property 'z'. Known properties are: a, b, c
        at com.charleskorn.kaml.YamlMapInput.throwUnknownProperty(YamlInput.kt:211)
        at com.charleskorn.kaml.YamlMapInput.decodeElementIndexForObject(YamlInput.kt:174)
        at com.charleskorn.kaml.YamlMapInput.decodeElementIndex(YamlInput.kt:159)
...
        at kotlinx.serialization.Decoder$DefaultImpls.decodeSerializableValue(Coders.kt:113)
        at kotlinx.serialization.ElementValueDecoder.decodeSerializableValue(ElementWise.kt:91)
        at kotlinx.serialization.CoreKt.decode(Core.kt:79)
        at com.charleskorn.kaml.Yaml.parse(Yaml.kt:40)
```

**Comment by charleskorn** [comment]
Hi @fvasco, thanks for the suggestion! I don't have a lot of capacity for this at the moment, but I will take a look when I get a chance.

If you'd be interested in submitting a PR to add this, I don't think it would be a big change and I'd be happy to provide feedback and suggestions as you go.

**Comment by charleskorn** [comment]
I found myself with some spare time so I've added this in and it'll be part of the next release - let me know if you have any feedback on the implementation!

**Comment by fvasco** [comment]
Sure,
thank you!

**Comment by DanySK** [comment]
Is this implemented? How to use it?

**Comment by charleskorn** [comment]
Hi @DanySK, yes, this is implemented. 

To enable strict mode, use the default settings (or set `YamlConfiguration.strictMode` to `true`). 

To disable strict mode, set `YamlConfiguration.strictMode` to `false`.
